language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

dist:
  - xenial

install:
  - pip install .

script:
  - python setup.py test

before_install:
  - pip install codecov
after_success:
  - codecov
